<a href="https://colab.research.google.com/github/catarina1532/python/blob/main/test3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vikasukani/forest-firearea-datasets")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/vikasukani/forest-firearea-datasets?dataset_version_number=1...

100%|██████████| 7.10k/7.10k [00:00<00:00, 9.48MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/vikasukani/forest-firearea-datasets/versions/1

gemini question: how do i read the file into a dataframe

In [41]:
import os
#List all files and directories in the specified path
for item in os.listdir(path):
  print(item)

forestfires.csv

In [43]:
import pandas as pd

#Replace 'path/to/your/file.csv' with the actual path to your file in Google Drive
df = pd.read_csv(path+'/'+'forestfires.csv')

#Display the first 5 rows of the Dataframe
display(df.head())

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [44]:
df.tail(20)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4   aug  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

In [45]:
df.dtypes

X          int64
Y          int64
month     object
day       object
FFMC     float64
DMC      float64
DC       float64
ISI      float64
temp     float64
RH         int64
wind     float64
rain     float64
area     float64
dtype: object

In [46]:
df['month'] #if i just want the months column

0      mar
1      oct
2      oct
3      mar
4      mar
      ...
512    aug
513    aug
514    aug
515    aug
516    nov
Name: month, Length: 517, dtype: object

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int64
 1   Y       517 non-null    int64
 2   month   517 non-null    object
 3   day     517 non-null    object
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
 12  area    517 non-null    float64
dtypes: float64(8), int64(3), object(2)
memory usage: 52.6+ KB

In [49]:
#Create a Series with the temperature values for all 517 fires
df['temp']

0       8.2
1      18.0
2      14.6
3       8.3
4      11.4
       ...
512    27.8
513    21.9
514    21.2
515    25.6
516    11.8
Name: temp, Length: 517, dtype: float64

In [48]:
#Create a DataFrame just with columns month and day
df[['month','day']]

    month  day
0     mar  fri
1     oct  tue
2     oct  sat
3     mar  fri
4     mar  sun
..    ...  ...
512   aug  sun
513   aug  sun
514   aug  sun
515   aug  sat
516   nov  tue

[517 rows x 2 columns]

In [50]:
df[df['temp']>25]

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0  0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0  0.00
30   6  3   sep  fri  94.3   85.1  692.3  15.9  25.4  24   3.6   0.0  0.00
45   5  6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0   0.0  0.00
55   4  3   sep  thu  92.9  137.0  706.4   9.2  27.7  24   2.2   0.0  0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...   ...
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  0.00
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0  0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  6.44
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  0.00

[65 rows x 13 columns]

In [ ]:
#Select fires that occured on weekends; use the conditional function .isin()
#i want to return a table where the value of the day is sat or sun (strings)
#nomes das linhas continuam a ser os índices

gemini question: select rows where 'day' is either 'sat' or 'sun'

In [52]:
weekend_df = df[df['day'].isin(['sat', 'sun'])]
display(weekend_df.head())

    X  Y month  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain  area
2   7  4   oct  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
4   8  6   mar  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5   8  6   aug  sun  92.3  85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
9   7  5   sep  sat  92.5  88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
10  7  5   sep  sat  92.5  88.0  698.6   7.1  17.8  51   7.2   0.0   0.0